package com.fwd.domain;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

@Entity
@Table(name = "page", uniqueConstraints = @UniqueConstraint(columnNames = {"code"}))
public class Pages implements Serializable {

    public static final String PRODUCT_TYPE = "PRODUCT";
    public static final String CUSTOMER_PLACE_TYPE = "CUSTOMER-PLACE";
    public static final String WHY_INSURANCE_TYPE = "WHY-INSURANCE";
    public static final String CELEBRATE_LIVING_TYPE = "CELEBRATE-LIVING";
    public static final String BEBAS_TYPE = "BEBAS";
    public static final String FOOTER_TYPE = "FOOTER";
    
    @Column(name = "code", table = "page", unique = false, updatable = true, insertable = true, nullable = false, length = 100, scale = 0, precision = 0)
    @Basic
    private String code;

    @Column(name = "breadcrumb", table = "page", unique = false, updatable = true, insertable = true, nullable = true, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String breadcrumb;

    @Column(name = "header_image_path", table = "page", unique = false, updatable = true, insertable = true, nullable = true, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String headerImagePath;

    @Transient
    private boolean headerImagePathChanged = false;
    
    @Column(name = "id_page", table = "page", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idPage;

    @Column(name = "type", table = "page", unique = false, updatable = true, insertable = true, nullable = false, length = 16, scale = 0, precision = 0)
    @Basic
    private String type;

    @Column(name = "title", table = "page", unique = false, updatable = true, insertable = true, nullable = true, length = 100, scale = 0, precision = 0)
    @Basic
    private String title;

    @Column(name = "icon_path", table = "page", unique = false, updatable = true, insertable = true, nullable = true, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String iconPath;

    @Transient
    private boolean iconPathChanged = false;
    
    @Column(name = "content", table = "page", unique = false, updatable = true, insertable = true, nullable = true, length = 2147483647, scale = 0, precision = 0)
    @Lob
    @Basic
    private String content;
    
    @Column(name = "orders", table = "page", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private int orders;
    
    @Column(name = "active", table = "page", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean active;
    
    @Column(name = "button_text", table = "page", unique = false, updatable = true, insertable = true, nullable = true, length = 100, scale = 0, precision = 0)
    @Basic
    private String buttonText;

    public Pages() {

    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getBreadcrumb() {
        return this.breadcrumb;
    }

    public void setBreadcrumb(String breadcrumb) {
        this.breadcrumb = breadcrumb;
    }

    public String getHeaderImagePath() {
        return this.headerImagePath;
    }

    public void setHeaderImagePath(String headerImagePath) {
        this.headerImagePath = headerImagePath;
    }

    public Long getIdPage() {
        return this.idPage;
    }

    public void setIdPage(Long idPage) {
        this.idPage = idPage;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getIconPath() {
        return this.iconPath;
    }

    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public int getOrders() {
        return this.orders;
    }

    public void setOrders(int orders) {
        this.orders = orders;
    }
    
    public boolean isActive() {
        return this.active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }
    
    public String getButtonText() {
        return this.buttonText;
    }

    public void setButtonText(String buttonText) {
        this.buttonText = buttonText;
    }

    public boolean isHeaderImagePathChanged() {
        return headerImagePathChanged;
    }

    public void setHeaderImagePathChanged(boolean headerImagePathChanged) {
        this.headerImagePathChanged = headerImagePathChanged;
    }

    public boolean isIconPathChanged() {
        return iconPathChanged;
    }

    public void setIconPathChanged(boolean iconPathChanged) {
        this.iconPathChanged = iconPathChanged;
    }
    
}
