package com.fwd.domain;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name="setting")
public class Profile implements Serializable {

    @Column(name="instagram_link",table="setting",nullable=false,length=50)
    @Basic
    private String instagramLink;

    @Column(name="address2",table="setting",length=65535)
    @Lob
    @Basic
    private String address2;

    @Column(name="address1",table="setting",nullable=false,length=65535)
    @Lob
    @Basic
    private String address1;

    @Column(name="hotline",table="setting",nullable=false,length=15)
    @Basic
    private String hotline;

    @Column(name="company_name",table="setting",nullable=false,length=100)
    @Basic
    private String companyName;

    @Column(name="twitter_link",table="setting",nullable=false,length=50)
    @Basic
    private String twitterLink;

    @Column(name="logo",table="setting",nullable=false,length=100)
    @Basic
    private String logo;
    
    @Transient
    private boolean logoChanged = false;

    @Column(name="youtube_link",table="setting",nullable=false,length=50)
    @Basic
    private String youtubeLink;

    @Column(name="id_profile",table="setting",nullable=false)
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    private Long idProfile;

    @Column(name="footer_description",table="setting",nullable=false,length=65535)
    @Lob
    @Basic
    private String footerDescription;

    @Column(name="email",table="setting",nullable=false,length=100)
    @Basic
    private String email;

    @Column(name="facebook_link",table="setting",nullable=false,length=50)
    @Basic
    private String facebookLink;
    
    @Column(name = "prime", table = "setting", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean prime;

    public Profile() {

    }
   
    public String getInstagramLink() {
        return this.instagramLink;
    }

    public void setInstagramLink(String instagramLink) {
        this.instagramLink = instagramLink;
    }
   
    public String getAddress2() {
        return this.address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }
   
    public String getAddress1() {
        return this.address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }
   
    public String getHotline() {
        return this.hotline;
    }

    public void setHotline(String hotline) {
        this.hotline = hotline;
    }
   
    public String getCompanyName() {
        return this.companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
   
    public String getTwitterLink() {
        return this.twitterLink;
    }

    public void setTwitterLink(String twitterLink) {
        this.twitterLink = twitterLink;
    }
   
    public String getLogo() {
        return this.logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }
   
    public String getYoutubeLink() {
        return this.youtubeLink;
    }

    public void setYoutubeLink(String youtubeLink) {
        this.youtubeLink = youtubeLink;
    }
   
    public Long getIdProfile() {
        return this.idProfile;
    }

    public void setIdProfile(Long idProfile) {
        this.idProfile = idProfile;
    }
   
    public String getFooterDescription() {
        return this.footerDescription;
    }

    public void setFooterDescription(String footerDescription) {
        this.footerDescription = footerDescription;
    }
   
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
   
    public String getFacebookLink() {
        return this.facebookLink;
    }

    public void setFacebookLink(String facebookLink) {
        this.facebookLink = facebookLink;
    }
    public boolean isPrime() {
        return this.prime;
    }

    public void setPrime(boolean prime) {
        this.prime = prime;
    }

    public boolean isLogoChanged() {
        return logoChanged;
    }

    public void setLogoChanged(boolean logoChanged) {
        this.logoChanged = logoChanged;
    }
    
}
