package com.fwd.domain;

//
// This file was generated by the JPA Modeler
//

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

@Entity
@Table(name = "testimonial")
public class Testimonial implements Serializable {

    @Column(name = "datetime", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Temporal(TemporalType.TIMESTAMP)
    @Basic
    private Date datetime;

    @Column(name = "website", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String website;

    @Column(name = "occupation", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 100, scale = 0, precision = 0)
    @Basic
    private String occupation;

    @Column(name = "image_background_path", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String imageBackgroundPath;
    
    @Transient
    private boolean imageBackgroundPathChanged = false;

    @Column(name = "name", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 100, scale = 0, precision = 0)
    @Basic
    private String name;

    @Column(name = "avatar_path", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String avatarPath;
    
    @Transient
    private boolean avatarPathChanged = false;
    
    @Column(name = "age", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private int age;

    @Column(name = "content", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 65535, scale = 0, precision = 0)
    @Lob
    @Basic
    private String content;

    @Column(name = "id_testimonial", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long idTestimonial;

    @Column(name = "prime", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean prime;
    
    @Column(name = "approval", table = "testimonial", unique = false, updatable = true, insertable = true, nullable = false, length = 255, scale = 0, precision = 0)
    @Basic
    private boolean approval;

    public Testimonial() {

    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }

    public String getWebsite() {
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getOccupation() {
        return this.occupation;
    }

    public void setOccupation(String occupation) {
        this.occupation = occupation;
    }

    public String getImageBackgroundPath() {
        return this.imageBackgroundPath;
    }

    public void setImageBackgroundPath(String imageBackgroundPath) {
        this.imageBackgroundPath = imageBackgroundPath;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAvatarPath() {
        return this.avatarPath;
    }

    public void setAvatarPath(String avatarPath) {
        this.avatarPath = avatarPath;
    }

    public int getAge() {
        return this.age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getIdTestimonial() {
        return this.idTestimonial;
    }

    public void setIdTestimonial(Long idTestimonial) {
        this.idTestimonial = idTestimonial;
    }

    public boolean isPrime() {
        return this.prime;
    }

    public void setPrime(boolean prime) {
        this.prime = prime;
    }
    
    public boolean isApproval() {
        return this.approval;
    }

    public void setApproval(boolean approval) {
        this.approval = approval;
    }

    public boolean isImageBackgroundPathChanged() {
        return imageBackgroundPathChanged;
    }

    public void setImageBackgroundPathChanged(boolean imageBackgroundPathChanged) {
        this.imageBackgroundPathChanged = imageBackgroundPathChanged;
    }

    public boolean isAvatarPathChanged() {
        return avatarPathChanged;
    }

    public void setAvatarPathChanged(boolean avatarPathChanged) {
        this.avatarPathChanged = avatarPathChanged;
    }
    
}
